services:
    website: 
        image: php:apache
        environment:
            - USERNAME=root
            - PASSWORD=root
        volumes:
            - ./website:/var/www/html
        depends_on:
            - supmit_api
        ports:
            - "8099:80"
    supmit_api:
        build: ./simple_api
        volumes:
            - ./simple_api/student_age.json:/data/student_age.json
        ports: 
            - "5000:5000"
        networks:
            - networkName
networks:
    networkName:
        driver: bridge
